# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ad7741e77738fa480266681e8381b57eb803cdbe24c00e9cfff45db61599d4c4306c5de0415e2df38864ec67ac6611f272f0a62881cfeca5582a9f9236cb31a9

test:
  secret_key_base: 45fd96dc2f7f1ed071783d1b020b0fa3a90e4129fa73783453cd94f5914fa2e35f1ebf34aa1f6f7f83bcb3156566f4fdc026f3f749b6a32658aee112f78305e2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
